apiVersion: v1
kind: Service
metadata:
  name: MultiPurposeEventSolution-svc
  labels:
    app: MultiPurposeEventSolution
spec:
  type: LoadBalancer
  selector:
    app: MultiPurposeEventSolution
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80