name: CD - Deploy App and Database

on:
  workflow_run:
    workflows: ["CI - build, test and push image to ACR"]
    types:
      - completed

env:
  ACR_LOGIN_SERVER: multipurposeacr.azurecr.io
  IMAGE_NAME: multipurposeapp
  K8S_NAMESPACE: testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Debug Secrets
        run: echo "Resource Group is ${{ secrets.AZURE_RESOURCE_GROUP }}"

      # 2. Deploy Azure SQL via Bicep
      - name: Deploy Azure SQL
        id: deploysql
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: infra/azure-sql.bicep
          parameters: >
            location=${{ secrets.AZURE_LOCATION }}
            sqlServerName=${{ secrets.AZURE_SQL_SERVER_NAME }}
            administratorLogin=${{ secrets.AZURE_SQL_ADMIN_LOGIN }}
            administratorLoginPassword=${{ secrets.AZURE_SQL_ADMIN_PASSWORD }}
            databaseName=${{ secrets.AZURE_SQL_DATABASE_NAME }}

      # Capture connection string output from Bicep
      - name: Set SQL Connection String
        run: echo "ConnectionStrings__DatabaseConnection=${{ steps.deploysql.outputs.sqlConnectionString }}" >> $GITHUB_ENV

      # 4. Set AKS Context
      - name: Set AKS Context
        uses: azure/aks-set-context@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      # 5. Deploy App to AKS
      - name: Deploy App
        run: |
          IMAGE=${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}
          sed "s|REPLACE_IMAGE|$IMAGE|g" k8s/deployment.yaml | kubectl -n ${{ env.K8S_NAMESPACE }} apply -f -
          kubectl -n ${{ env.K8S_NAMESPACE }} apply -f k8s/service.yaml
          kubectl -n ${{ env.K8S_NAMESPACE }} rollout status deployment/app-api-deployment --timeout=120s

      # Run EF Core migrations using the environment variable
      - name: Run EF Core migrations
        run: |
          dotnet tool install --global dotnet-ef
          dotnet ef database update